version: "3"
services:
  traefik:
    image: docker.io/traefik:v3.2.1
    environment:
      - TZ=Europe/Berlin
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
      - "8080:8080" # Don't do this in production!
    volumes:
      - ${DATA_VOLUME}/traefik:/etc/traefik
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik-dashboard.testside.section77.de`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.tls=true"